# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "test-harness"
edition = "2024"

[features]
default = ["openssl", "vendored"]

# `openssl` and `symcrypt` are mutually exclusive; see the root crate's manifest.
openssl = ["ms-tcg-tpm-sys/openssl"]
symcrypt = ["ms-tcg-tpm-sys/symcrypt"]
vendored = ["ms-tcg-tpm-sys/vendored"]

[dependencies]
getrandom = { version = "0.4", default-features = false }
ms-tcg-tpm-sys = { path = "../", default-features = false }

tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lints]
workspace = true
