# Copyright (C) Microsoft Corporation. All rights reserved.

[package]
name = "test-harness"
edition = "2024"

[features]
default = ["openssl", "vendored"]

openssl = ["ms-tcg-tpm-sys/openssl"]
vendored = ["ms-tcg-tpm-sys/vendored"]

[dependencies]
getrandom = { version = "0.4", default-features = false }
ms-tcg-tpm-sys = { path = "../", default-features = false }

tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lints]
workspace = true
