#!/usr/bin/env bash
# Copyright (C) Microsoft Corporation. All rights reserved.
#
# Stage a prebuilt SymCrypt from the latest `microsoft/openvmm-deps` release.
#
# The release ships a cross-compilation sysroot that contains the SymCrypt
# headers plus `libsymcrypt.a`, a static build of SymCrypt's
# `symcrypt_generic_posix` module. This script pulls just those files out and
# lays them out as the `SYMCRYPT_INCLUDE_DIR` / `SYMCRYPT_LIB_DIR` pair that
# `build.rs` expects.

set -euo pipefail

REPO="microsoft/openvmm-deps"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${REPO_ROOT}/.symcrypt"
TAG=""
ARCH=""

usage() {
    cat <<'EOF'
Usage: fetch-symcrypt.sh [--dest DIR] [--tag TAG] [--arch ARCH]

  --dest DIR   Where to stage SymCrypt. Default: <repo>/.symcrypt
  --tag TAG    openvmm-deps release tag. Default: the latest release.
  --arch ARCH  x86_64 or aarch64. Default: derived from `uname -m`.

Writes DIR/include and DIR/lib, then points SYMCRYPT_INCLUDE_DIR and
SYMCRYPT_LIB_DIR at them via the workspace's .cargo/config.toml, so plain
`cargo build --no-default-features --features symcrypt` picks them up. In GitHub Actions the
assignments are also appended to $GITHUB_ENV.
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dest) DEST="$2"; shift 2 ;;
        --tag) TAG="$2"; shift 2 ;;
        --arch) ARCH="$2"; shift 2 ;;
        -h | --help) usage; exit 0 ;;
        *) echo "unknown argument: $1" >&2; usage >&2; exit 1 ;;
    esac
done

if [[ -z "$ARCH" ]]; then
    case "$(uname -m)" in
        x86_64 | amd64) ARCH="x86_64" ;;
        aarch64 | arm64) ARCH="aarch64" ;;
        *) echo "unsupported host architecture: $(uname -m)" >&2; exit 1 ;;
    esac
fi

case "$ARCH" in
    x86_64 | aarch64) ;;
    *) echo "unsupported architecture: $ARCH" >&2; exit 1 ;;
esac

# `Authorization` is optional, but avoids the low unauthenticated rate limit.
api_curl() {
    if [[ -n "${GITHUB_TOKEN:-}" ]]; then
        curl -fsSL -H "Authorization: Bearer ${GITHUB_TOKEN}" "$@"
    else
        curl -fsSL "$@"
    fi
}

if [[ -z "$TAG" ]]; then
    TAG="$(api_curl "https://api.github.com/repos/${REPO}/releases/latest" |
        sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' |
        head -n 1)"
    if [[ -z "$TAG" ]]; then
        echo "failed to resolve the latest ${REPO} release" >&2
        exit 1
    fi
fi

ASSET="openvmm-deps.${ARCH}.${TAG}.tar.gz"
URL="https://github.com/${REPO}/releases/download/${TAG}/${ASSET}"

echo "fetching SymCrypt from ${URL}" >&2

STAGING="$(mktemp -d)"
trap 'rm -r "$STAGING"' EXIT

# The release tarball nests the sysroot as `./sysroot.tar.gz`, so unwrap the
# outer archive on the fly rather than spilling ~150MiB of unrelated artifacts
# to disk.
curl -fsSL "$URL" |
    tar -xzO ./sysroot.tar.gz |
    tar -xz -C "$STAGING" --wildcards './include/symcrypt*' './lib/libsymcrypt.a'

if [[ ! -f "$STAGING/lib/libsymcrypt.a" ]]; then
    echo "${ASSET} did not contain lib/libsymcrypt.a" >&2
    exit 1
fi

# Resolve `--dest` to an absolute path before deleting anything.
DEST_NAME="$(basename "$DEST")"
case "$DEST_NAME" in
    "" | "." | ".." | "/")
        echo "refusing to stage SymCrypt into ${DEST}" >&2
        exit 1
        ;;
esac
DEST="$(cd "$(dirname "$DEST")" && pwd)/${DEST_NAME}"

# Replace the previous staging wholesale, so nothing stale survives an upgrade.
rm -r "$DEST"
mkdir -p "$DEST"
mv "$STAGING/include" "$STAGING/lib" "$DEST/"

# Cargo applies `[env]` to build scripts, so this is what actually hands the
# paths to `build.rs`. Entries do not override an already-set variable.
CARGO_CONFIG="${REPO_ROOT}/.cargo/config.toml"
MARKER="# Generated by scripts/fetch-symcrypt.sh"
if [[ -e "$CARGO_CONFIG" ]] && ! head -n 1 "$CARGO_CONFIG" | grep -qxF "$MARKER"; then
    echo "refusing to overwrite hand-written ${CARGO_CONFIG}" >&2
    exit 1
fi

# Backslashes and quotes are the only characters TOML basic strings can't hold.
toml_escape() {
    printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

mkdir -p "$(dirname "$CARGO_CONFIG")"
cat > "$CARGO_CONFIG" <<EOF
${MARKER}
[env]
SYMCRYPT_INCLUDE_DIR = "$(toml_escape "$DEST/include")"
SYMCRYPT_LIB_DIR = "$(toml_escape "$DEST/lib")"
EOF

echo "set SYMCRYPT_INCLUDE_DIR and SYMCRYPT_LIB_DIR in ${CARGO_CONFIG}" >&2

if [[ -n "${GITHUB_ENV:-}" ]]; then
    {
        printf 'SYMCRYPT_INCLUDE_DIR=%s\n' "$DEST/include"
        printf 'SYMCRYPT_LIB_DIR=%s\n' "$DEST/lib"
    } >> "$GITHUB_ENV"
fi
